spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 24kobebryant8
    driver-class-name: com.mysql.cj.jdbc.Driver
